var a = [10, 20, 30];
var b = [1, 2, 4];
var flowers = ["작약", "목단", "수국", "철쭉"];
console.log(a);
console.log(b);
console.log(flowers);
var person;
person = ["홍길동", 25, "양천구 신목동역"];
console.log(person);
console.log(person[0]);
console.log(person[1]);
console.log(person[2]);
